# Cloudflare Pages 배포 설정
name = "grap"
compatibility_date = "2024-01-01"

# 참고: Cron 작업은 GitHub Actions를 통해 실행됩니다.
# .github/workflows/cron-jobs.yml 파일을 참조하세요.

# Pages 환경 변수 설정 (실제 값은 Cloudflare Dashboard에서 설정)
[env.production.vars]
NODE_ENV = "production"

# Preview 환경 설정 (development 대신 preview 사용)
[env.preview.vars]
NODE_ENV = "development"
