name = "grap"# Cloudflare Pages 배포 설정
#name = "grap"
#compatibility_date = "2024-01-01"

# 환경 변수 설정 (실제 값은 Cloudflare Dashboard에서 설정)
#[env.production.vars]
#NODE_ENV = "production"

# 개발 환경 설정
#[env.development.vars]
#NODE_ENV = "development"

# 빌드 설정
#[build]
#command = "npm run build"
#cwd = "."
#watch_dir = "."

# Pages 설정
#[pages]
#build_output_dir = ".output/public"
#compatibility_date = "2024-01-01"
